trigger: 
  branches:
     include:
       - main

pool:
 vmImage:  ubuntu-latest

stages:
  - stage: Terraformvalidation
    displayName: Terraform Validate

    jobs:
      - job: Validate
        
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          
  
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Env/Dev'
              backendServiceArm: 'tushar'
              backendAzureRmStorageAccountName: 'tusharstorage420'
              backendAzureRmContainerName: 'container'
              backendAzureRmKey: 'tushar.tfstate'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'tushar'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Env/Dev'
              


              